-- liquibase formatted sql

-- changeset maksimf:1
CREATE TABLE IF NOT EXISTS notification_task (
    id bigint generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id bigint NOT NULL,
    message_text text NOT NULL,
    notification_date_time TIMESTAMP NOT NULL
)